version: "3.9"

services:

  pg-db:
    image: marceloeugenios/desafio-dev-db:latest
    ports:
       - "5432:5432"
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
       - PGADMIN_DEFAULT_EMAIL=admin@desafio.dev
       - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
       - "5555:80"

# docker-compose -f docker-compose-dev.yml