version: "3.9"

services:

  pg-db:
    image: marceloeugenios/desafio-dev-db:latest
    ports:
       - "5432:5432"
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:16.1.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    restart: always
    volumes:
      - keycloak_data:/data
      - keycloak_data:/opt/jboss/keycloak/providers
      - keycloak_data:/opt/jboss/keycloak/standalone/configuration

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
       - PGADMIN_DEFAULT_EMAIL=admin@desafio.dev
       - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
       - "5555:80"

volumes:
  keycloak_data: