CREATE TABLE arquivo
  (
     id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
     data_upload TIMESTAMP,
     nome        VARCHAR(200),
     PRIMARY KEY (id)
  );

CREATE TABLE transacao
  (
     id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
     cartao         VARCHAR(12),
     cpf            VARCHAR(11),
     data_transacao TIMESTAMP,
     loja_dono      VARCHAR(100),
     loja_nome      VARCHAR(100),
     valor          DECIMAL(19, 2),
     PRIMARY KEY (id)
  );

CREATE TABLE transacao_tipo
  (
     id                 INTEGER NOT NULL,
     descricao          VARCHAR(200),
     transacao_natureza VARCHAR(255),
     PRIMARY KEY (id)
  );