CREATE TABLE arquivo
  (
     id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
     data_upload TIMESTAMP,
     nome        VARCHAR(200),
     usuario_id  BINARY NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE transacao_tipo
  (
     id                 INTEGER NOT NULL,
     descricao          VARCHAR(200),
     transacao_natureza VARCHAR(50),
     PRIMARY KEY (id)
  );

CREATE TABLE transacao
  (
     id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
     cartao          VARCHAR(12),
     cpf             VARCHAR(11),
     data_transacao  TIMESTAMP,
     loja_dono       VARCHAR(100),
     loja_nome       VARCHAR(100),
     valor           DECIMAL(19, 2),
     _transacao_tipo INTEGER NOT NULL,
     _arquivo        INTEGER NOT NULL,
     PRIMARY KEY (id),
     CONSTRAINT fk5iybhdf0moubkadd7hr8t7qmi FOREIGN KEY (_arquivo) REFERENCES
     arquivo,
     CONSTRAINT fkdi6uq8ydrlc9lv40sreflni7d FOREIGN KEY (_transacao_tipo)
     REFERENCES transacao_tipo
  );