server:
  port: 8088

spring:
  jpa:
    open-in-view: false
    hibernate:
      show_sql: true
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio_db
    username: desafio
    password: desafio

keycloak:
  auth-server-url: http://localhost:8080
  realm: desafio-dev-app
  resource: desafio-dev-client
  credentials:
    secret: Xl399B3uPhGIxULvjDIXyumZB3Kl0ruA
  use-resource-role-mappings: true
  bearer-only: true

app:
  authorization-uri: http://localhost:8080/realms/desafio-dev-app/protocol/openid-connect/token
  user-info-uri: http://localhost:8080/realms/desafio-dev-app/protocol/openid-connect/userinfo
  token-uri: http://localhost:8080/realms/desafio-dev-app/protocol/openid-connect/token
  logout: http://localhost:8080/realms/desafio-dev-app/protocol/openid-connect/logout
  authorization-grant-type: password
  scope: profile email

logging:
  level:
    root: INFO