spring:
  jpa:
    open-in-view: false
    hibernate:
    show_sql: true
    format_sql: true
    generate-ddl: true
    ddl-auto: none
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
