spring:
  jpa:
    open-in-view: false
    hibernate:
      show_sql: true
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://desafio-dev-db:5432/desafio_db
    username: desafio
    password: desafio
